<a href="https://colab.research.google.com/github/BATTI-CHANDAN-SINGH/Batch_22_-2303A51515-python/blob/main/Lab_03_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1D Array
import numpy as np
arr1 = np.array([1,3,4])
print(arr1)

#2d Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)



[1 3 4]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[2 7 0 8 1]


In [ ]:
#Zero Array
zero_arr = np.zeros((2,3))
print(zero_arr)

#Ones Array
ones_arr = np.ones((2,3))
print(ones_arr)

#range of number
range_arr = np.arange(0,10,1)
print(range_arr)

#random Array
random_arr = np.random.randint(0,10,5)
print(random_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[3 3 4 3 2]


In [ ]:
#Array Attributes
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)

(2, 3)
int64
6
2
8


In [ ]:
#indexing and Slicing
#1D Array
arr = np.array([10,20,30,40])
print("first element",arr[0])
print("second element",arr[1])
print("last element",arr[-1])
print("first two element",arr[0:2])
print("last two element",arr[-2:])
print("first three element",arr[:3])
print("reverse array",arr[::-1])
print("reverse array",arr[::-2])
print("slice[1:4]", arr[1:4])

#2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("first row",arr[0])
print("second row",arr[1])
print("third row",arr[2])
print("first element of first row",arr[0,0])
print("first element of second row",arr[1,0])
print("first element of third row",arr[2,0])
print("first two element of first row",arr[0,0:2])
print("first two element of second row",arr[1,0:2])
print("first two element of third row",arr[2,0:2])
print("first two element of first row",arr[0:2,0])
print("first two element of second row",arr[0:2,1])
print("first two element of third row",arr[0:2,2])

first element 10
second element 20
last element 40
first two element [10 20]
last two element [30 40]
first three element [10 20 30]
reverse array [40 30 20 10]
reverse array [40 20]
slice[1:4] [20 30 40]
first row [1 2 3]
second row [4 5 6]
third row [7 8 9]
first element of first row 1
first element of second row 4
first element of third row 7
first two element of first row [1 2]
first two element of second row [4 5]
first two element of third row [7 8]
first two element of first row [1 4]
first two element of second row [2 5]
first two element of third row [3 6]


In [ ]:
#Array Operations
#Arithmetic
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Addition",arr1+arr2)
print("Subtraction",arr1-arr2)
print("Multiplication",arr1*arr2)
print("Division",arr1/arr2)
print("Exponent",arr1**arr2)
print("Modulus",arr1%arr2)
print("Dot Product",np.dot(arr1,arr2))
print("power",np.power(arr1,arr2))

#Mathemaitcal Functions
arr = np.array([1,2,3])
print("sin",np.sin(arr))
print("cos",np.cos(arr))
print("tan",np.tan(arr))
print("log",np.log(arr))
print("exp",np.exp(arr))


Addition [5 7 9]
Subtraction [-3 -3 -3]
Multiplication [ 4 10 18]
Division [0.25 0.4  0.5 ]
Exponent [  1  32 729]
Modulus [1 2 3]
Dot Product 32
power [  1  32 729]
sin [0.84147098 0.90929743 0.14112001]
cos [ 0.54030231 -0.41614684 -0.9899925 ]
tan [ 1.55740772 -2.18503986 -0.14254654]
log [0.         0.69314718 1.09861229]
exp [ 2.71828183  7.3890561  20.08553692]
sum 6
mean 2.0
median 2.0
standard deviation 0.816496580927726


In [ ]:
arr = np.array([[1,2,3],[2,3,4]])
print("sum",np.sum(arr))
print("mean",np.mean(arr))
print("median",np.median(arr))
print("standard deviation",np.std(arr))
print("variance",np.var(arr))
print("minimum",np.min(arr))
print("maximum",np.max(arr))
print("argmin",np.argmin(arr))
print("argmax",np.argmax(arr))
print("sort",np.sort(arr))
print("concatenate",np.concatenate((arr1,arr2)))
print("stack",np.stack((arr1,arr2)))
print("vstack",np.vstack((arr1,arr2)))
print("hstack",np.hstack((arr1,arr2)))
print("transpose",np.transpose(arr1))
print("sum along 0", np.sum(arr, axis=0))
print("sum along 1", np.sum(arr, axis=1))


sum 15
mean 2.5
median 2.5
standard deviation 0.9574271077563381
variance 0.9166666666666666
minimum 1
maximum 4
argmin 0
argmax 5
sort [[1 2 3]
 [2 3 4]]
concatenate [1 2 3 4 5 6]
stack [[1 2 3]
 [4 5 6]]
vstack [[1 2 3]
 [4 5 6]]
hstack [1 2 3 4 5 6]
transpose [1 2 3]
sum along 0 [3 5 7]
sum along 1 [6 9]


In [ ]:
#Broadcasting
a=np.array([1,2,3])
b=5
print("Add Scalar to array", a+b)
print("Sub Scalar to array", a-b)
print("Mul Scalar to array", a*b)
print("Div Scalar to array", a/b)
print("Mod Scalar to array", a%b)
print("Exp Scalar to array", a**b)

c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("Add Scalar to array", c+d)
print("Sub Scalar to array", c-d)
print("Mul Scalar to array", c*d)
print("Div Scalar to array", c/d)
print("Mod Scalar to array", c%d)

Add Scalar to array [6 7 8]
Sub Scalar to array [-4 -3 -2]
Mul Scalar to array [ 5 10 15]
Div Scalar to array [0.2 0.4 0.6]
Mod Scalar to array [1 2 3]
Exp Scalar to array [  1  32 243]
Add Scalar to array [[5 6 7]
 [6 7 8]
 [7 8 9]]
Sub Scalar to array [[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]
Mul Scalar to array [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Div Scalar to array [[0.25       0.2        0.16666667]
 [0.5        0.4        0.33333333]
 [0.75       0.6        0.5       ]]
Mod Scalar to array [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("matrix mulplication:\n", np.dot(A,B))
print("Transpose:\n",A.T)
print("Inverse:\n",np.linalg.inv(A))
print("Determinant:\n",np.linalg.det(A))

matrix mulplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant:
 -2.0000000000000004


In [45]:
#simple Program -Student Marks Analyis
import numpy as nd
#Maks of student in  3 subjects
marks = nd.array([[85,90,88],[88,79,87],[85,80,100]])
print("Average per student ",nd.mean(marks, axis=1))
print("Average per subject", nd.mean(marks, axis=0))
print("Highest marks each subject", nd.max(marks, axis=0))
print("Lowest marks each subject", nd.min(marks, axis=0))
print("Student with the highest total marks", nd.argmax(nd.sum(marks, axis=1)) + 1)
print("Subject with the lowest average score", nd.argmin(nd.mean(marks, axis=0)) + 1)

Average per student  [87.66666667 84.66666667 88.33333333]
Average per subject [86.         83.         91.66666667]
Highest marks each subject [ 88  90 100]
Lowest marks each subject [85 79 87]
Student with the highest total marks 3
Subject with the lowest average score 2
